AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an EC2 with two security groups that enable SSH and HTML
Resources:
  MyEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063 # most recent ami id of Amazon Linux2
      InstanceType: t2.micro
      KeyName: burakawskey # pem file name without extension
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref HTMLSecurityGroup
      UserData: 
         Fn::Base64:
                |
             #!/bin/bash
             sudo yum update -y
      Tags:
        - Key: Name
          Value: EC2_2security_groups
  
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  HTMLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTML access via port 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
